redis:
  image: redis:latest
  command: redis-server --appendonly yes

web:
  build: .
  environment:
    - REDIS_HOST=redis
  env_file: .env
  links:
    - redis:redis
  ports:
    - 5000
  command: gunicorn -b 0.0.0.0:5000 app:app
